ddd_list = [{"DDD": 11, "cidade": "São Paulo – SP"},
            {"DDD": 12, "cidade": "São José dos Campos – SP"},
            {"DDD": 13, "cidade": "Santos – SP"},
            {"DDD": 14, "cidade": "Bauru – SP"},
            {"DDD": 15, "cidade": "Sorocaba – SP"},
            {"DDD": 16, "cidade": "Ribeirão Preto – SP"},
            {"DDD": 17, "cidade": "São José do Rio Preto – SP"},
            {"DDD": 18, "cidade": "Presidente Prudente – SP"},
            {"DDD": 19, "cidade": "Campinas – SP"},
            {"DDD": 21, "cidade": "Rio de Janeiro – RJ"},
            {"DDD": 22, "cidade": "Campos dos Goytacazes – RJ"},
            {"DDD": 24, "cidade": "Volta Redonda – RJ"},
            {"DDD": 27, "cidade": "Vitória / Vila Velha – ES"},
            {"DDD": 28, "cidade": "Cachoeiro de Itapemirim – ES"},
            {"DDD": 31, "cidade": "Belo Horizonte – MG"},
            {"DDD": 32, "cidade": "Juiz de Fora – MG"},
            {"DDD": 33, "cidade": "Governador Valadares – MG"},
            {"DDD": 34, "cidade": "Uberlândia – MG"},
            {"DDD": 35, "cidade": "Poços de Caldas – MG"},
            {"DDD": 37, "cidade": "Divinópolis – MG"},
            {"DDD": 38, "cidade": "Montes Claros – MG"},
            {"DDD": 41, "cidade": "Curitiba – PR"},
            {"DDD": 42, "cidade": "Ponta Grossa – PR"},
            {"DDD": 43, "cidade": "Londrina – PR"},
            {"DDD": 44, "cidade": "Maringá – PR"},
            {"DDD": 45, "cidade": "Foz do Iguaçú – PR"},
            {"DDD": 46, "cidade": "Pato Branco / Francisco Beltrão – PR"},
            {"DDD": 47, "cidade": "Joinville – SC"},
            {"DDD": 48, "cidade": "Florianópolis – SC"},
            {"DDD": 49, "cidade": "Chapecó – SC"},
            {"DDD": 51, "cidade": "Porto Alegre – RS"},
            {"DDD": 53, "cidade": "Pelotas – RS"},
            {"DDD": 54, "cidade": "Caxias do Sul – RS"},
            {"DDD": 55, "cidade": "Santa Maria – RS"},
            {"DDD": 61, "cidade": "Brasília – DF"},
            {"DDD": 62, "cidade": "Goiânia – GO"},
            {"DDD": 63, "cidade": "Palmas – TO"},
            {"DDD": 64, "cidade": "Rio Verde – GO"},
            {"DDD": 65, "cidade": "Cuiabá – MT"},
            {"DDD": 66, "cidade": "Rondonópolis – MT"},
            {"DDD": 67, "cidade": "Campo Grande – MS"},
            {"DDD": 68, "cidade": "Rio Branco – AC"},
            {"DDD": 69, "cidade": "Porto Velho – RO"},
            {"DDD": 71, "cidade": "Salvador – BA"},
            {"DDD": 73, "cidade": "Ilhéus – BA"},
            {"DDD": 74, "cidade": "Juazeiro – BA"},
            {"DDD": 75, "cidade": "Feira de Santana – BA"},
            {"DDD": 77, "cidade": "Barreiras – BA"},
            {"DDD": 79, "cidade": "Aracaju – SE"},
            {"DDD": 81, "cidade": "Recife – PE"},
            {"DDD": 82, "cidade": "Maceió – AL"},
            {"DDD": 83, "cidade": "João Pessoa – PB"},
            {"DDD": 84, "cidade": "Natal – RN"},
            {"DDD": 85, "cidade": "Fortaleza – CE"},
            {"DDD": 86, "cidade": "Teresina – PI"},
            {"DDD": 87, "cidade": "Petrolina – PE"},
            {"DDD": 88, "cidade": "Juazeiro do Norte – CE"},
            {"DDD": 89, "cidade": "Picos – PI"},
            {"DDD": 91, "cidade": "Belém – PA"},
            {"DDD": 92, "cidade": "Manaus – AM"},
            {"DDD": 93, "cidade": "Santarém – PA"},
            {"DDD": 94, "cidade": "Marabá – PA"},
            {"DDD": 95, "cidade": "Boa Vista – RR"},
            {"DDD": 96, "cidade": "Macapá – AP"},
            {"DDD": 97, "cidade": "Coari – AM"},
            {"DDD": 98, "cidade": "São Luís – MA"},
            {"DDD": 99, "cidade": "Imperatriz – MA"}]
